#pragma once

#define EFFEKSEER_MAX_PARTICLE 10000
#define EFFEKSEER_EFFECT_MAX 32

enum EffekseerEffectType
{
	EFFEKSEER_PLAYER_DAMAGE,
	EFFEKSEER_PLAYER_NORMAL_SHOT_HIT,
	EFFEKSEER_PLAYER_LOCK_ON,
	EFFEKSEER_BEE_SHOT_HIT,
	EFFEKSEER_BEE_DEAD,
	EFFEKSEER_BARRIER,
	EFFEKSEER_GUARD,
	EFFEKSEER_EFFECT_TYPE_MAX
};
